name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-documentation:
    name: Build LaTeX Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Build PDFs
        working-directory: docs
        run: |
          make all

      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdfs
          path: docs/*.pdf
