name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  placeholder:
    name: Placeholder CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Placeholder Step
        run: echo "No code to test yet. Placeholder CI workflow executed successfully."
